# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install .
  - yes | pip uninstall pytest
  - pip install pytest>=3.0.4
script:
    py.test
